- src/commands/build.rs
- src/commands/local.rs
- src/ops.rs
I move the format logic for appending the archive directory and the `oci-archive:` prefix in the `generate_full_image` function. This also fixes using the wrong string for the `rebase` command.
> fix: Rebase path not being generated properly

- README.md
- install.sh
- templates/Containerfile
Trying to make the action install the binary from the container on GHCR with `podman run --rm ghcr.io/blue-build/cli:main-installer | sudo bash` (like in the README). Getting some error and this _might_ be related and might not, but shouldn't hurt to merge either, since I just made the `cli` package public.
> chore: use GHCR for install.sh

- README.md
- install.sh
Related to https://github.com/blue-build/github-action/issues/5
> fix: Install script not working as intended

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- .github/workflows/tag.yml
- Earthfile
This makes it so that the main branch will push images but PRs won't. This also puts integration tests back in the `+all` target.
> fix: Improve workflow for main branch and PRs

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- .github/workflows/tag.yml
- Earthfile
- Builds on main and tags will use the `medium` satellite that uses `x4` rate on build minutes
- This gives us larger cache and more memory
- Builds on PRs will use the `small` satellite that uses `x2` rate on build minutes
- We are using the starter tier which gives us `10000` build minutes per month and caching for our builds to make them faster
> chore: Setup earthly satellite building

- templates/Containerfile
https://github.com/ublue-os/bling/blob/main/Containerfile the containerfile copies an empty folder in these locations for backwards compatability. `/tmp/files` and `/tmp/rpms` have been deprecated from bling, all of the RPMs have mostly moved to COPR or ublue-os/config
> fix: remove deprecated bling `COPY` for `files` and `rpms`

- .github/workflows/build-pr.yml
This fixes workflow runs from PRs that use forks of the repo and don't contain the secret for the earthly login
> fix: only use earthly builder if token exists

- src/commands/build.rs
- src/constants.rs
This change will follow the patter that was established with the GitLab pipeline. Users will be able to have their images signed by GitHub's OIDC. This will allow users to rebase directly onto a signed image and forego using the siging module.
> feat: Use GitHub's OIDC for signing images

- Earthfile
required for running the bluebuild CLI directly from podman (needed for latest version of bluebuild for github action)
> feat: use WORKDIR and ENTRYPOINT for cli containers

- templates/Containerfile
This allows scripts to create as many files as they need in /tmp and /var without having to worry about them being included in the final image. Now the last instruction will only be the ostree container commit
> feat: Use tmpfs mount for /tmp and /var

- src/commands/build.rs
the `SIGSTORE_ID_TOKEN` env var is not declared inside of github actions, however the block that does OIDC signing requires it, this changes it so that it matches for `GITHUB_TOKEN` in the second block instead of `SIGSTORE_ID_TOKEN`, (hopefully) using OIDC instead of pubkey auth
> fix: check for `GITHUB_TOKEN` instead of `SIGSTORE_ID_TOKEN` for github OIDC

- templates/Containerfile
After setting up the tmpfs mount for /var, rpm-ostree started to not have cache throughout the single build. This creates a cache for rpm-ostree that is tied to the specific recipe being built. This will allow subsequent builds of a recipe to be faster and not interfere with the cache of another recipe, especially if they are on different OS versions
> feat: Make use of rpm-ostree cache

- templates/export.sh
Trailing newlines is something that we will never need as an information, so it can only cause issues with parsing yaml values.
I scratched my head for 10 minutes on why my variable has a trailing newline when I use `readarray -t` everywhere. Then I remembered get_yaml_array function.
This should not affect current working modules at all, but it would be good to test before landing.
> fix: Remove trailing newlines from yaml arrays

- src/commands/bug_report.rs
- src/commands/build.rs
- src/commands/build/build_strategy.rs
- src/commands/local.rs
- src/commands/template.rs
- src/constants.rs
- src/module_recipe.rs
- src/ops.rs
- templates/Containerfile
To keep things as consistent as possible, we're switching to using the GITHUB_TOKEN env var for login instead. Env vars were also all pulled out into their own constants to make things more consistent.
This change also includes prioritizing public/private key signing over OIDC keyless for GitHub for an easier transition. It would require the user to delete their `cosign.pub` file from their repo in order to start using the keyless method.
> refactor: Use GITHUB_TOKEN instead of REGISTRY_TOKEN

- src/commands/build.rs
- src/ops.rs
An issue was filed for adding retry logic to our push_image command in the CLI. https://github.com/blue-build/cli/issues/79.
This PR adds:
- **retry flag**
- `-r`
- defaults to true 
- **retry_count flag**
- `--retry_count`
- defaults to 1
This functionality will be extended to our other services in build (podman api as well once that is hooked up), but this is the initial ground work
> feat: add retry options to cli build command

- template/templates/Containerfile.j2
- template/templates/modules/modules.j2
Since the command `ostree container commit` checks for the presence of mounted directories, we will be running it at the end of each module run. We have also updated the final commit to remove from /tmp/ and /var/ again in case a user creates extra files through custom instructions.
Closes #101 #95
> fix: Run `ostree container commit` at the end of each module run

- template/templates/modules/modules.j2
https://github.com/blue-build/cli/issues/118#issuecomment-1992536977
as mentioned here reverting to the bash files module simplifies the build process (and allows for better usage of `ostree container commit`). It also means there are less overall layers and (ideally) a smaller image as a result. Tested locally and template generation seems to work just fine
> feat: revert to bash files module

- .github/workflows/build-pr.yml
- src/commands/build.rs
- src/commands/local.rs
- src/drivers.rs
- src/drivers/docker_driver.rs
- src/drivers/opts.rs
- src/drivers/opts/build.rs
- src/drivers/podman_driver.rs
- src/drivers/skopeo_driver.rs
- src/image_metadata.rs
- src/lib.rs
This fix involves creating a new function for the `BuildDriver` trait called `build_tag_push`. In order to get the proper logic in place to make use of `docker buildx`, I had to create a separate function that would construct the build command to include all of the tags necessary for pushing. A default implementation of `build_tag_push` will be used for `podman` and `buildah` which was originally from the build command's functions. Now that we have custom logic for docker builds, we can take advantage of using the GitHub cache features without having the `--load` arg which had a big negative effect on build times. We can now also use docker for creating local `oci-archive` tarballs for local rebasing. Making use of the `oci-archive` will require the user to create a `docker-container` …
> fix: Allow docker driver to properly use cache

- src/commands/build.rs
- src/drivers.rs
- src/drivers/buildah_driver.rs
- src/drivers/docker_driver.rs
- src/drivers/opts/build.rs
- src/drivers/podman_driver.rs
All supported versions of podman, buildah, and docker support the zstd compression format. This format should allow users to pull less data when updating their computers.
> feat: Support `zstd` compression

- template/templates/Containerfile.j2
This exists in the legacy template:
https://github.com/blue-build/legacy-template/blob/489ebea77b79bd722679352bf8c75f185562e3b6/build.sh#L13C1-L13C39
And is also used in many modules, though with `MODULE_DIRECTORY="${MODULE_DIRECTORY:-"/tmp/modules"}"` to not break things.
And is documented on the website, because I assumed it existed: https://blue-build.org/reference/module/#module_directory
I know this probably won't change much, but it's still useful for the scripts.
> chore: add MODULE_DIRECTORY env var

- README.md
I had initially added distrobox installation instructions to the website (see [here](https://github.com/blue-build/website/pull/45), but it has been suggested that the CLI readme is a more natural place for them.
I have tested the distrobox installation method and procedures on my home machine and aside from an odd bug (see https://github.com/blue-build/cli/issues/145) everything is working.
> docs: add distrobox installation tips

- src/commands/build.rs
Resolves #147
`cosign sign` only signs the provided digest by default. If that digest is a manifest which is currently the default for images built with Docker due to https://docs.docker.com/build/attestations/attestation-storage/, we also want to sign each image with `--recursive` so that they can be pulled by any container managers which enforce that (e.g. podman).
Refer to https://github.com/sigstore/cosign/blob/main/doc/cosign_sign.md for more details.
> fix: Sign all images in manifest

- README.md
A few more tips/tricks I wrote for https://github.com/blue-build/website/pull/45 that make more sense in the README
> README: add alpine distrobox and shell completions

- src/commands.rs
- src/commands/build.rs
- src/commands/template.rs
- src/drivers.rs
- src/drivers/types.rs
There are 2 new args available that allow the user to specify which program to use for building and inspecting images. If the user doesn't provide an argument, the tool will determine which program to use like it has been.
Help text:
```
Build an image from a recipe
Usage: bluebuild build [OPTIONS] [RECIPE]
Arguments:
[RECIPE]
The recipe file to build an image
Options:
-p, --push
Push the image with all the tags.
Requires `--registry`, `--username`, and `--password` if not building in CI.
-c, --compression-format <COMPRESSION_FORMAT>
The compression format the images will be pushed in
[default: gzip]
[possible values: gzip, zstd]
-n, --no-retry-push
Block `bluebuild` from retrying to push the image
--retry-count <RETRY_COUNT>
The number of times to retry pushing the image
[default: 1]
-f, …
```
> feat: Add driver selection args

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- Earthfile
- build.rs
- src/commands/template.rs
- template/src/lib.rs
- template/templates/modules/modules.j2
I noticed that making changes to the exports script before a release could cause modules to not build properly if breaking changes got pushed out. To prevent this, I'm making it so that the hash of the commit is put in the tag for the exports script image and that the CLI tool will use that hash when building the `Containerfile`.
> chore: Cleanup images and use hash for exports tag

- recipe/src/module.rs
- recipe/src/recipe.rs
Previous implementation wasn't taking into account the modules failing to be read properly and were just being ignored. This changes that to error out if any `from-file:` usage doesn't deserialize properly.
> fix: Error if any module fails to deserialize

- integration-tests/test-repo/recipes/akmods.yml
- recipe/src/module.rs
This change updates the akmods module to pull the new nvidia images. The new property will be a boolean with property name of `nvidia`. If a user continues to use the old `nvidia-version` property, a warning will be printed telling them to switch to the new property. The old images will still be allowed to be used to support backwards compatibility.
> chore: Update akmods module to account for upstream changes

- Cargo.lock
- Cargo.toml
- recipe/src/recipe.rs
- src/commands/template.rs
- utils/Cargo.toml
- utils/build.rs
- utils/highlights/Dockerfile.sublime-syntax
- utils/src/lib.rs
- utils/src/syntax_highlighting.rs
As I was re-arranging my recipe files, I needed a way to ensure that the order of my recipe is correct without having to read through the generated `Containerfile`. So I added a `-d`/`--display-full-recipe` arg to `template` that will print out all of your modules in the order defined by following the `from-file` property.
```
$> bluebuild template --help
Generate a Containerfile from a recipe
Usage: bluebuild template [OPTIONS] [RECIPE]
Arguments:
[RECIPE]
The recipe file to create a template from
Options:
-o, --output <OUTPUT>
File to output to instead of STDOUT
--registry <REGISTRY>
The registry domain the image will be published to.
This is used for modules that need to know where the image is being published (i.e. the signing module).
--registry-namespace <REGISTRY_NAMESPACE>
The …
```
> feat: Display full recipe with syntax highlighting

- integration-tests/test-repo/recipes/recipe.yml
- recipe/src/recipe.rs
This adds the ability for the user to add alternate tags to their images. These are designed to replace the `latest` and timestamp (e.g. `20240429`) tags.
> feat: Add alternate tags for user images

- Cargo.lock
- src/bin/bluebuild.rs
- src/commands/generate.rs
- utils/Cargo.toml
- utils/src/ctrlc_handler.rs
- utils/src/lib.rs
- utils/src/logging.rs
This allows spawned children processes to be killed when a user performs a Ctrl-C operation. Before this change, children processes would end up continuing in the background with the user unaware.
> fix: Add Ctrl-C handler for spawned children

- .helix/languages.toml
- Cargo.lock
- Cargo.toml
- recipe/Cargo.toml
- recipe/src/module.rs
- recipe/src/module_ext.rs
- recipe/src/recipe.rs
- recipe/src/stage.rs
- recipe/src/stages_ext.rs
- src/commands.rs
- src/commands/bug_report.rs
- src/commands/build.rs
- src/commands/completions.rs
- src/commands/generate.rs
- src/commands/local.rs
- src/commands/switch.rs
- src/drivers.rs
- src/drivers/buildah_driver.rs
- src/drivers/docker_driver.rs
- src/drivers/podman_driver.rs
- src/drivers/skopeo_driver.rs
- src/rpm_ostree_status.rs
- utils/Cargo.toml
- utils/src/lib.rs
- utils/src/syntax_highlighting.rs
Switch to a better error crate that will allow setting help texts for any error we want.
> refactor: Switch to using miette for errors instead of anyhow

- .github/workflows/build-pr.yml
- Earthfile
- recipe/src/recipe.rs
- src/commands/build.rs
- src/commands/generate.rs
- src/drivers.rs
- src/drivers/cosign_driver.rs
- src/drivers/github_driver.rs
- src/drivers/github_driver/event.rs
- src/drivers/gitlab_driver.rs
- src/drivers/local_driver.rs
- src/drivers/traits.rs
- src/drivers/types.rs
- src/lib.rs
- template/src/lib.rs
- template/templates/Containerfile.j2
- test-files/github-events/branch.json
- test-files/github-events/default-branch.json
- test-files/github-events/pr-branch.json
- utils/src/constants.rs
- utils/src/lib.rs
Creating a CI Driver that allows us to separate out logic for the various CI systems. This will allow easier extensibility when adding more implementations later.
> refactor: Create CiDriver

- modules.json
- template/templates/modules/containerfile/containerfile.tsp
- template/templates/modules/containerfile/module.yml
- template/templates/modules/copy/README.md
- template/templates/modules/copy/copy.tsp
- template/templates/modules/copy/module.yml
The website build process now uses the GitHub API to generate a global `modules.json`. If you decide to move the directory containing all the modules, please tell me, or make a PR changing [this line](https://github.com/blue-build/website/blob/9eb198c4e532e82e70b980da955b87f39ce663b4/astro.config.mjs#L102). If you don't, I'll find out anyways, because the website builds will break. 
Also, whenever updating the modules, make sure the schema is updated too to match the current state of the module. If you need help with writing [TypeSpec](https://typespec.io/), consult me, but you probably wont, since it's just a type system kind of like TypeScript's or Rust's .
> fix: add typespec schemas for cli modules, remove modules.json (not needed anymore)

- template/templates/Containerfile.j2
Take a look at this issue for more details:
https://github.com/blue-build/modules/issues/314
Idk if anything else needs to be done, please tell
Should be tested for regressions too
> chore: Move files from `/usr/etc/` to `/etc/` in build-time

- utils/src/constants.rs
This changes the Dockerfile to pull the cosign container image from GHCR instead of Google Cloud. This helps the Sigstore team manage their cloud spend (as GHCR is provided for free and Google Cloud Artifact Registry is not).
Note the container hash does not change and images are posted to both locations upon cosign's release process.
> fix: switch cosign registry from GCR to GHCR

- Cargo.lock
- Cargo.toml
- bacon.toml
- integration-tests/Earthfile
- integration-tests/test-repo/recipes/invalid-module.yml
- integration-tests/test-repo/recipes/invalid-stages.yml
- integration-tests/test-repo/recipes/recipe-invalid-from-file.yml
- recipe/src/lib.rs
- recipe/src/stages_ext.rs
- src/commands/validate.rs
- src/commands/validate/location.rs
- src/commands/validate/schema_validator.rs
- src/commands/validate/yaml_span.rs
- utils/Cargo.toml
This adds in the ability to highlight the errors in the recipe files for the user to see.
> feat: Use yaml-rust2 to get line numbers for better errors

- flake.nix
- scripts/pre_build.sh
- scripts/setup.sh
- template/templates/Containerfile.j2
> chore: Install jq and prefer over yq for modules

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- integration-tests/Earthfile
- process/drivers/docker_driver.rs
- process/drivers/docker_driver/metadata.rs
- process/drivers/types.rs
This is blocking https://github.com/blue-build/modules/issues/364 and #261  as we need a patch to go out but, multi-arch inspection was not setup correctly. I forgot to actually build `arm` and `amd` versions of our images, and after getting that working, image inspections started to fail. This PR will allow inspecting multi-arch images.
> fix: Add logic for inspecting multi-manifest images

- Cargo.toml
- process/Cargo.toml
- process/drivers.rs
- process/drivers/buildah_driver.rs
- process/drivers/docker_driver.rs
- process/drivers/opts/build.rs
- process/drivers/podman_driver.rs
- process/drivers/traits.rs
- process/logging.rs
- src/bin/bluebuild.rs
- src/commands.rs
- src/commands/prune.rs
- src/commands/switch.rs
I got tired of running prune for all the different build systems we support so I decided to make a new command. This will be considered a breaking change cause it requires a `buildah` version of at least `1.29` up from the current `1.24`.
> feat(prune)!: Create prune command

- scripts/exports.sh
This fixes the issue with `files` module in this [PR](https://github.com/blue-build/modules/pull/369), where brackets are included in an array.
> chore: Assure that `get_json_array` outputs compact `json` output

- integration-tests/test-repo/recipes/recipe.yml
- template/templates/Containerfile.j2
Supplements main PR: https://github.com/blue-build/modules/pull/375
Tests & it works, can be merged.
> chore: Copy signing keys to `/etc/` only

- process/drivers.rs
- scripts/exports.sh
- scripts/setup.sh
This will make it work for Ubuntu versions, where it's `24.04` or similar. Or if some distros use letters for VERSION_IDs.
Please tell me if I escaped quotes correctly in `drivers.rs`
> chore: Use consistent syntax for getting information from os-release

- README.md
the blue-build/template repo has these files ending in .yml not .yaml so probably should here as well
> docs: change file paths to match template

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- justfile
- process/drivers/opts/rechunk.rs
- process/drivers/traits.rs
- src/commands/build.rs
- utils/src/constants.rs
I've noticed some strangeness when it comes to using rechunk on a image that is based off of a rechunked image. Mostly my initramfs is being truncated and not being loaded on boot, so this is an attempt to enable the use of fresh rechunking by not supplying the previous ref of the image.
> feat: Allow fresh rechunking of image

- bacon.toml
- integration-tests/test-repo/modules/test-nu-modules/test-nu-modules.nu
- integration-tests/test-repo/recipes/recipe.yml
- integration-tests/test-repo/recipes/stages.yml
- recipe/src/module.rs
- recipe/src/recipe.rs
- scripts/run_module.sh
- src/commands/validate/yaml_span.rs
- template/src/lib.rs
- template/templates/Containerfile.j2
- template/templates/modules/modules.j2
- template/templates/stages.j2
- utils/src/constants.rs
> feat: Add support for NuShell scripts

- .github/workflows/build-pr.yml
- Cargo.lock
- integration-tests/test-repo/recipes/recipe-gts.yml
- recipe/src/lib.rs
- recipe/src/maybe_version.rs
- recipe/src/recipe.rs
- src/commands/generate.rs
- template/src/lib.rs
- template/templates/Containerfile.j2
- template/templates/modules/modules.j2
- template/templates/stages.j2
- utils/Cargo.toml
- utils/src/semver.rs
This will allow our users to set `nushell-version` and `blue-build-tag` to the value of `none` to prevent the binaries from being added to the image. Since we have multiple modules that will be using nushell, I made sure to mount the nushell binaries into the image if the value is set to `none`.
> fix: Allow user to not install Nushell in their system

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- .github/workflows/flakehub-tagged.yml
- .github/workflows/tag.yml
- .github/workflows/zizmor.yml
some of the actions are out of date, for example `astral-sh/setup-uv` is on 5.X.X now but has breaking changes, so I left it alone
Other actions that don't have semantic versioning like ublue's remove-unwanted-software were left at the existing version, even if new versions are available
> chore: pin actions to commit hashes

- recipe/src/akmods_info.rs
- recipe/src/module.rs
- template/templates/modules/akmods/akmods.j2
When using fedora 42 with the main images, the build will fail due to the non-existing akmods-extra images.
It looks like, these images will only exist for the `bazzite` based ones.
> fix: pull akmods-extra only for bazzite (Fixes #441)

- integration-tests/test-repo/recipes/common.yml
- justfile
- process/drivers/buildah_driver.rs
- process/drivers/docker_driver.rs
- process/drivers/podman_driver.rs
- utils/src/secret.rs
So @RoyalOughtness brought up some pain points about the first iteration of secrets. This change allows users to specify the mount type so they can mix and match where they get the secret from and where they put it in the build.
This is a breaking change; however, this feature hasn't been announced yet and I'm fairly sure that @RoyalOughtness is the only one who's tried it out since I've been talking about it in Discord. I don't usually want to do something like this, but I think this would be a much better format.
> fix!: Allow specifying mount type for secrets

- process/drivers.rs
- process/drivers/buildah_driver.rs
- process/drivers/docker_driver.rs
- process/drivers/docker_driver/metadata.rs
- process/drivers/github_driver.rs
- process/drivers/gitlab_driver.rs
- process/drivers/local_driver.rs
- process/drivers/opts/build.rs
- process/drivers/opts/ci.rs
- process/drivers/opts/inspect.rs
- process/drivers/opts/rechunk.rs
- process/drivers/opts/signing.rs
- process/drivers/podman_driver.rs
- process/drivers/skopeo_driver.rs
- process/drivers/traits.rs
- process/drivers/types.rs
- src/commands/build.rs
- src/commands/generate.rs
This add support for building images for all platforms that are supported by `podman` and `docker`. This will be the pre-cursor to [adding support for specifying platforms to build in the recipe](https://github.com/blue-build/cli/issues/340) and closes #499 .
According to the `podman-build` man page, [this](https://go.dev/doc/install/source#environment) is the source for all platform variants.
> feat: Add all linux platforms
